language: php

#sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - 7
  
mysql:
  database: websiteCMS
  username: root
#  password: test
  encoding: utf8
  
before_install:
  - sudo apt-get update > /dev/null
  
install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql php5 apache2

before_script:
#  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
#  - dir
  - mysql -e 'create database websiteCMS'
  - php build/install.php

script:
   - wget http://localhost/
#  - cd ./80/
#  - phpunit index.php
